name: 'Set-up Environment Variables'
description: 'Read and set environment variables from the appropriate file'
inputs:
  ENVIRONMENT:
    description: 'The environment to set up'
    required: true
outputs:
  JAVA_VERSION:
    description: 'The Java version'
  JAVA_DISTRIBUTION:
    description: 'The Java distribution'
    
runs:
  using: 'composite'
  steps:
    - run: |
        if [[ "${{ inputs.ENVIRONMENT }}" == "dev" ]]; then
          source ./.github/workflows/reusable/setup-env-var/snapshot-env
        else
          source ./.github/workflows/reusable/setup-env-var/snapshot-env
        fi
        echo "::set-output name=JAVA_VERSION::$JAVA_VERSION"
        echo "::set-output name=JAVA_DISTRIBUTION::$JAVA_DISTRIBUTION"
        echo "::set-output name=MAVEN_OPTIONS::$MAVEN_OPTIONS"
      shell: bash