#!/bin/bash
JAVA_VERSION=$1
JAVA_DISTRIBUTION=$2
echo JAVA_VERSION: $JAVA_VERSION
echo JAVA_DISTRIBUTION: $JAVA_DISTRIBUTION

echo "::set-output name=JAVA_VERSION::$JAVA_VERSION"
echo "::set-output name=JAVA_DISTRIBUTION::$JAVA_DISTRIBUTION"