name: 'Setup'
description: 'Setup variables and environment'
runs:
  using: "composite"
  steps:
    - name: setup variables
      id: var-setup
      run: |
        MAVEN_PROFILE_NAME="release"
        SERVER_USERNAME=$2
        SERVER_PASSWORD=$3
        ./.github/workflows/composite/setup/setup-env-var/setup.sh $MAVEN_PROFILE_NAME $SERVER_USERNAME $SERVER_PASSWORD
      shell: bash
      
    - name: setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ steps.var-setup.outputs.JAVA_VERSION }}
        distribution: ${{ steps.var-setup.outputs.JAVA_DISTRIBUTION }}
        cache: maven
      
    - name: Configure git bot
      run: | 
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
      shell: bash
