name: 'Setup'
description: 'Setup variables and environment'
outputs:
  JAVA_VERSION:
    description: 'Java version'
  JAVA_DISTRIBUTION:
    description: 'Java distribution'
  MAVEN_GROUP_ID:
    description: 'Maven group ID'
  MAVEN_OPTS:
    description: 'Maven options'
  MAVEN_SET_VERSION_OPTS:
    description: 'Maven set version options'
  MAVEN_PROFILE_NAME:
    description: 'Maven profile name'
inputs: 
  PROFILE: 
    type: string
    required: false
    description: maven profile
    default: snapshot

runs:
  using: "composite"
  steps:
    - name: setup variables
      id: var-setup
      run: |
        MAVEN_PROFILE_NAME="${{inputs.PROFILE}}"
        SERVER_USERNAME=$2
        SERVER_PASSWORD=$3
        ./.github/workflows/composite/setup/setup-env-var/setup.sh $MAVEN_PROFILE_NAME $SERVER_USERNAME $SERVER_PASSWORD
      shell: bash
      
    - name: setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        cache: maven
      
    - name: Configure git bot
      run: | 
        echo "environment"
        echo ${{env.ENVIRONMENT}}
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
      shell: bash
