name: 'Setup'
description: 'Setup variables and environment'
runs:
  using: "composite"
  steps:
    - name: print
      run: |
        MAVEN_PROFILE_NAME="release"
        SERVER_USERNAME=$2
        SERVER_PASSWORD=$3
        ./.github/workflows/reusable/setup-env-var/setup.sh $MAVEN_PROFILE_NAME $SERVER_USERNAME $SERVER_PASSWORD
      shell: bash  
    - name: Create maven settings
      run: ./.github/workflows/reusable/scripts/create-maven-settings.sh ${{ inputs.REPOSITORY_URL }} ${{ inputs.SERVER_ID }} ${{ inputs.SERVER_USERNAME }} ${{ inputs.SERVER_PASSWORD }}
      shell: bash
