name: 'Maven settings'
description: 'create maven settings'
runs:
  using: "composite"
  steps:
    - name: Create maven settings
      run: ./.github/workflows/reusable/scripts/create-maven-settings.sh
      env:
          SERVER_ID:        ${{ secrets.SERVER_ID }}
          REPOSITORY_URL:   ${{ secrets.REPOSITORY_URL }} 
          SERVER_USERNAME:  ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD:  ${{ secrets.GITHUB_TOKEN }}
