name: 'Maven settings'
description: 'create maven settings'
inputs:
  ENVIRONMENT:
    type: string
    required: true
    default: 'dev'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - name: Create maven settings
      run: ./.github/workflows/reusable/scripts/create-maven-settings.sh
      env:
          SERVER_ID:        ${{ secrets.SERVER_ID }}
          REPOSITORY_URL:   ${{ secrets.REPOSITORY_URL }} 
          SERVER_USERNAME:  ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD:  ${{ secrets.GITHUB_TOKEN }}
