name: Build Snapshot

on:
  push:
    branches:
      'dev-*'
  pull_request_target:
      types:
        - closed
      branches:
        - 'dev'
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    environment: dev
    steps: 
      - uses: actions/checkout@v3
      - name: dump context
        uses: ./.github/workflows/composite/dump-context
        
      - name: Setup environment and variables
        uses: ./.github/workflows/composite/setup
      
      - name: Create maven settings
        run: |
          ./.github/workflows/reusable/scripts/create-maven-settings.sh ${{ secrets.REPOSITORY_URL }} ${{ secrets.SERVER_ID }} ${{ secrets.SERVER_USERNAME }} ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        
      - name: Build & Test
        run: |
          mvn -P snapshot clean install ${{ steps.var-setup.outputs.MAVEN_OPTS }}
      
  deploy:
    needs: build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Int server
        uses: ./.github/workflows/composite/deploy
        with:
          PROFILE: "snapshot"
          BRANCH: "dev"
          REPOSITORY_URL: ${{ secrets.REPOSITORY_URL }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
         
  next-snapshot-iteration:
    runs-on: ubuntu-latest
    name: Set next dev iteration
    needs: deploy
    if: success()
    environment: dev
    steps: 
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/setup
            
      - name: Create maven settings
        run: |
          ./.github/workflows/reusable/scripts/create-maven-settings.sh ${{ secrets.REPOSITORY_URL }} ${{ secrets.SERVER_ID }} ${{ secrets.SERVER_USERNAME }} ${{ secrets.GITHUB_TOKEN }}
        shell: bash
      
      - name: Create and push next dev iteration
        run: |
          mvn -P snapshot build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT
          MVN_ARTIFACT_ID=$(./.github/workflows/reusable/scripts/get-artifact.sh)
          VERSION=$(./.github/workflows/reusable/scripts/get-version.sh)
          MAJOR=$(cut -d'.' -f1 <<<"$VERSION") MINOR=$(cut -d'.' -f2 <<<"$VERSION")
           
          #  mvn -P snapshot versions:update-parent -DparentVersion=[$MAJOR.$MINOR.0-SNAPSHOT,$MAJOR.$MINOR.999-SNAPSHOT] -DallowSnapshots=true -DgenerateBackupPoms=false
           
          git commit -am "set next snapshot $VERSION"
          git push origin dev
          
  sonar:
    runs-on: ubuntu-latest
    environment: dev
    name: Analyse
    needs: next-snapshot-iteration
    steps: 
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/sonar
    
  field-build-notification:
    runs-on: ubuntu-latest
    environment: dev
    name: Send error message to Teams channel
    needs: build
    if: failure()
    steps: 
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/composite/ms-teams
