name: Build Snapshot

on:
  push:
    branches:
      'dev-*'
  pull_request_target:
      types:
        - closed
      branches:
        - 'dev'
  workflow_dispatch:

permissions:
  packages: write
  contents: write

env:
  SERVER: "github"
  PROFILE: "snapshot"
  MAVEN_OPTS: -DgenerateBackupPoms=false -Dsurefire.skipTests=false
  SERVER_USERNAME: "MaxIvanenqo"
  REPOSITORY_URL: "https://maven.pkg.github.com/MaxIvanenqo/workflow-concept"
jobs:
  dump:
    name: Dump workflow context
    uses: ./.github/workflows/dump-context.yml    

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    environment: dev
    steps: 
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: maven
      
      - name: Create maven settings
        run: ./.github/workflows/reusable/scripts/create-maven-settings.sh
        env:
          PROFILE: "snapshot"
          REPOSITORY_ID: "snapshot"
          REPOSITORY_SNAPSHOTS_ENABLED: true
          REPOSITORY_RELEASES_ENABLED: false
          REPOSITORY_URL: ${{env.REPOSITORY_URL}} 
          SERVER_ID: ${{env.SERVER}}
          SERVER_USERNAME: ${{env.SERVER_USERNAME}}
          SERVER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build & Test
        run: |
          mvn -P ${{ env.PROFILE }} clean install ${{ env.MAVEN_OPTS }}
      
  deploy:
    if: github.event.pull_request.merged == true
    needs: build
    uses: ./.github/workflows/deploy.yml
    with: 
      activeProfile: "snapshot"
      activeEnvironment: "dev"
         
  setNextDevIteration:
    runs-on: ubuntu-latest
    name: Set next dev iteration
    needs: deploy
    if: success()
    steps: 
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: maven
      
      - name: Configure git bot
        run: | 
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Create maven settings
        run: ./.github/workflows/reusable/scripts/create-maven-settings.sh
        env:
          PROFILE: "snapshot"
          REPOSITORY_ID: "snapshot"
          REPOSITORY_SNAPSHOTS_ENABLED: true
          REPOSITORY_RELEASES_ENABLED: false
          REPOSITORY_URL: ${{env.REPOSITORY_URL}} 
          SERVER_ID: ${{env.SERVER}}
          SERVER_USERNAME: ${{env.SERVER_USERNAME}}
          SERVER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit next DEV iteration
        run: |
          
          mvn -P ${{ env.PROFILE }} build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT
          
          MVN_ARTIFACT_ID=$(./.github/workflows/reusable/scripts/get-artifact.sh)
          VERSION=$(./.github/workflows/reusable/scripts/get-version.sh)
          MAJOR=$(cut -d'.' -f1 <<<"$VERSION") MINOR=$(cut -d'.' -f2 <<<"$VERSION")
        
          mvn -P ${{ env.PROFILE }} versions:update-parent -DparentVersion=[$MAJOR.$MINOR.0-SNAPSHOT,$MAJOR.$MINOR.999-SNAPSHOT] -DallowSnapshots=true -DgenerateBackupPoms=false
         
          git commit -am "set next snapshot $VERSION"
          
  sonar:
    name: Analyse
    needs: build
    uses: ./.github/workflows/sonar.yml
       
  mail:
    name: Share analysis report
    needs: sonar
    if: always()
    uses: ./.github/workflows/mail.yml

  field-build-notification:
    name: Send build error message to Teams channel
    needs: build
    if: failure()
    uses: ./.github/workflows/teams-int.yml
    
