name: Deploy

on:
  workflow_call:
    inputs:
        activeProfile:
            description: Profile to be activated in maven
            type: string
            required: true

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    name: Deploy package
    runs-on: ubuntu-latest
    environment: ${{ inputs.activeEnvironment }}
    steps: 
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{secrets.JAVA_VERSION}}
          distribution: 'zulu'
          cache: maven

      - name: Create maven settings
        run: ./.github/workflows/reusable/scripts/create-maven-settings.sh
        env:
          SERVER_ID:        ${{ secrets.SERVER }}
          REPOSITORY_URL:   ${{ secrets.REPOSITORY_URL }} 
          SERVER_USERNAME:  ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD:  ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git bot
        run: | 
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"

      - name: Deploy package to ${{ env.SERVER }} 
        run: |
          git fetch
          git checkout ${{inputs.branch}}
          mvn -P ${{ inputs.activeProfile }} clean deploy -DaltDeploymentRepository=github::default::${{secrets.REPOSITORY_URL}} ${{ secrets.MAVEN_OPTS }}

  failed-deploy-notification:
    name: Send deploy error message to Teams channel
    needs: deploy
    if: failure()
    uses: ./.github/workflows/teams-int.yml
    
