name: Report

on: 
  workflow_call:

jobs:
    report:
      name: Send report via email
      runs-on: ubuntu-latest
      steps: 
        - name: Send
          run: |
            echo "Integration to be implemented"