name: Test connection

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Connect
    runs-on: ubuntu-latest
    environment: dev
    steps: 
      - uses: actions/checkout@v3

      - run: | 
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${{ secrets.AZURE_VM_PRIVATE_KEY }}"
            ssh maxivanenqo@137.117.196.11
        shell: bash
     