name: Test connection

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Connect
    runs-on: ubuntu-latest
    environment: dev
    steps: 
      - uses: actions/checkout@v3
        env:
            AZURE_VM_PRIVATE_KEY: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
      - run: | 
            mkdir -p /home/runner/.ssh
            echo "${AZURE_VM_PRIVATE_KEY}" > /home/runner/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh -i /home/runner/.ssh/id_rsa maxivanenqo@137.117.196.11
        shell: bash
     