name: Test connection

on:
  workflow_dispatch:
  
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    environment: dev
    steps: 
      - uses: actions/checkout@v3
      - run: | 
            echo "Start"
            sudo apt-get install sshpass -y
            
        shell: bash
     